#!/usr/bin/env python3
"""Generate STRUCTURE_MANIFEST.md for the repository."""

from __future__ import annotations

import hashlib
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SKIP_DIRS = {".git", ".serena", "target", "__pycache__"}
SKIP_FILE_PREFIXES = ("__tmp",)
SKIP_FILE_MARKERS = (".bak-",)
MANIFEST = "STRUCTURE_MANIFEST.md"
MANIFEST_CONTEXT = (
    "Generated by `scripts/generate_structure_manifest.py` during Phase 102 "
    "structure-manifest consistency validation. The manifest is a generated "
    "repository inventory used by local and CI structure checks; refresh it "
    "after governed file, script, source, workflow, or documentation changes."
)


def included_files() -> list[pathlib.Path]:
    files: list[pathlib.Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(ROOT)
        if relative.as_posix() == MANIFEST:
            continue
        if any(part in SKIP_DIRS for part in relative.parts):
            continue
        if relative.name.startswith(SKIP_FILE_PREFIXES):
            continue
        if any(marker in relative.name for marker in SKIP_FILE_MARKERS):
            continue
        files.append(path)
    return sorted(files, key=lambda path: path.relative_to(ROOT).as_posix())


def main() -> int:
    rows = []
    for path in included_files():
        relative = path.relative_to(ROOT).as_posix()
        data = path.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        rows.append(f"| `{relative}` | {len(data)} | `{digest}` |")

    lines = [
        "# STRUCTURE_MANIFEST.md",
        "",
        MANIFEST_CONTEXT,
        "",
        "Note: this manifest intentionally excludes `STRUCTURE_MANIFEST.md` itself to avoid self-referential hash drift.",
        "",
        "## File Manifest",
        "",
        "| Path | Bytes | SHA-256 |",
        "|---|---:|---|",
        *rows,
    ]
    (ROOT / MANIFEST).write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
